# update-links.ps1

# プロジェクトのルートディレクトリを取得 (このファイルの親フォルダを基準にする)
$PROJECT_DIR = (Get-Location).Path
$INDEX_FILE = "$PROJECT_DIR\index.html"

# nursing-school-site フォルダ内の HTML ファイル一覧を取得 (index.html を除く)
$FILES = Get-ChildItem -Path $PROJECT_DIR -Filter *.html -Recurse | Where-Object { $_.Name -ne "index.html" }

# HTML リンクリストを作成
$LINKS = ""
foreach ($FILE in $FILES) {
    $FILENAME = $FILE.Name
    $TITLE = ($FILENAME -replace '.html', '') -replace '-', ' '
    $TITLE = $TITLE.Substring(0,1).ToUpper() + $TITLE.Substring(1)
    $LINKS += "<li><a href=`"$FILENAME`">$TITLE</a></li>`n"
}

# index.html のバックアップを作成
Copy-Item $INDEX_FILE "$INDEX_FILE.bak" -Force

# index.html にリンクリストを自動追加
$INDEX_CONTENT = Get-Content $INDEX_FILE -Raw
$UPDATED_CONTENT = $INDEX_CONTENT -replace '(<!-- AUTOGENERATED LINKS START -->).*?(<!-- AUTOGENERATED LINKS END -->)', "`$1`n$LINKS`$2"

# 更新内容を index.html に保存
Set-Content -Path $INDEX_FILE -Value $UPDATED_CONTENT
